### PR TITLE
feat: initial commit including protobuf generated code + appender.

### PR DESCRIPTION
**Pull request by adrianbenavides**
## Description

Creates repository to hold components of [gazzete's core](https://github.com/gazette/core) rewritten in rust. This PR includes:

* `protocol` crate to generate protobuf code out of gazzete's core [`broker/protocol.proto`](https://github.com/gazette/core/blob/master/broker/protocol/protocol.proto) file.

* `broker` crate that includes the `Appender` (go's version [here](https://github.com/gazette/core/blob/master/broker/client/appender.go)) component. The main differences in the internal implementation are due to how the `.proto` code is generated: go's implementation works around the concept of implementing the `io.Writer` interface, while rust's implementation does it around the `futures::stream` trait. 

### Async streams

The Append RPC consumes a request that implements a `tonic::IntoStreamingRequest<T>`, which internally uses an async stream (as defined in [`futures`](https://docs.rs/futures/latest/futures/stream/index.html) crate).

To create an async stream without having to implement the `Future` trait, I've used [`async-stream`](https://docs.rs/async-stream/latest/async_stream/). The reason why this is the preferred way to work with async streams is explained in the [`tokio::stream` docs](https://docs.rs/tokio/latest/tokio/stream/index.html).

### Other resources

* [tonic's grpc tutorial](https://github.com/hyperium/tonic/blob/master/examples/routeguide-tutorial.md)
* [discussion](https://users.rust-lang.org/t/i-need-to-implement-asyncread-and-asyncwrite-but-dont-know-where-to-get-started/57945) about different approaches on how to implement the `AsyncRead` and `AsyncWrite` traits
* for future refactors implementing AsyncRead/Write: https://github.com/devashishdxt/mock-io/blob/main/src/mock_stream/tokio.rs

### CODE REVIEW

**Review by jgraettinger — CHANGES_REQUESTED** [review]
Thanks! Off to a great start. Comments below.

> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-:-MuEFjuC8CPJ-1FX3P4O:b-ulw9hu)* status: all files reviewed, 9 unresolved discussions (waiting on @adrianbenavides)

___
*[broker/src/client/appender.rs, line 48 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuE1XU082ohjf_5VlK8:-MuE1XU082ohjf_5VlK9:b-rr36gm) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/appender.rs#L48)):*
> ```XML
> 
>         let (res_tx, res_rx) = oneshot::channel();
>         // TODO: could the channel size be parametrized somehow?
> ```

The gRPC internals also keep a buffer, and the protocol will further have an in-flight buffer between server & client that's dynamically negotiated.
I would think this specific buffer size can be quite tight, perhaps just one.

Not looking for changes right now, just want to talk through this: how did you decide between this imperative API with an internal stream channel, vs one where the appender _takes_ a stream of StreamOp?
___
*[broker/src/client/appender.rs, line 63 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuE4osB5ZGOYA5UzX6Z:-MuE4osB5ZGOYA5UzX6_:b-5s2qlu) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/appender.rs#L63)):*
> ```XML
>     /// Each `AsyncRead` is read from byte zero until EOF, and may be read multiple times.
>     /// If no `AsyncRead`s are provided, an Append RPC with no content is issued.
>     #[tracing::instrument(level = "debug", skip(rjc, request, readers), fields(journal = % request.journal))]
> ```

I got a little confused why you were taking on so much scope (retries, pulling from `AsyncRead`) in this function,
and then realized that you're mirroring the [Append](https://github.com/gazette/core/blob/master/broker/client/appender.go#L153) free-function in appender.go. :thumbsup: 

FWIW, I wouldn't really consider that part of the `Appender` interface, but absolutely see how that's confusing given the context.
Perhaps it should live in the `broker::client` module? To my knowledge, `Append()` isn't much used outside of some limited test-case uses.
Github's reference linking gives the false impression it is, when in actuality `client.Append()` calls are calling the gRPC Append() RPC method stub and not this free function.
In production code, retries are handled by `AppendService`, and the prevailing practice is to _produce_ bytes into a buffered writer offered up by `AppendService` rather than pulling from a reader as is done by `Append()`. Apologies for the confusion. If you'd rather, you can drop this function altogether. Either way!
___
*[broker/src/client/appender.rs, line 119 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuE7DfT9Fqvg7DYYXO7:-MuE7DfT9Fqvg7DYYXO8:b-h8vj5t) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/appender.rs#L119)):*
> ```XML
>     /// Write a chunk of bytes to the `Appender` async stream. The stream must be initialized
>     /// calling the `init` method before doing any write.
>     async fn write(&mut self, buf: Vec<u8>) -> ClientResult<()> {
> ```

This should probably take bytes::Bytes to avoid copies.
___
*[broker/src/client/appender.rs, line 164 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuE97hm3BUXor-ZBVPZ:-MuE97hnEOzcwcnxvA9H:b-r9vfy7) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/appender.rs#L164)):*
> ```XML
>             loop {
>                 let mut request = request.clone();
>                 // The Append RPC won't try to read the next stream message until it doesn't fully processed. If the message is
> ```

nit: grammar.
___
*[broker/src/client/appender.rs, line 178 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuE9Mew4L7Gm8W8A2m7:-MuE9Mew4L7Gm8W8A2m8:bgyu1tj) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/appender.rs#L178)):*
> ```XML
>                         // for the broker's ACK.
>                         match op {
>                             StreamOp::Init => {
> ```

Could you always yield `request` immediately prior to entering this loop, and then drop the `StreamOp::Init` variant altogether?
___
*[broker/src/client/appender.rs, line 187 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuE9iz7CBQN2twjdrsX:-MuE9iz7CBQN2twjdrsY:b-e04whb) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/appender.rs#L187)):*
> ```XML
>                             StreamOp::Write(buf) => {
>                                 // Send write request.
>                                 request.content = buf;
> ```

Rather than cloning `request` above, I'd recommend an explicit `yield pb::AppendRequest { content: buf, ...Default::default() }`.
Nothing of value is actually being copied over by the clone (in fact, it's incorrect as written because there may be other metadata fields set beyond `journal`),
and with the explicit literal construction it's clearer to the reader exactly what's being returned.
___
*[broker/src/client/appender.rs, line 203 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuEANUTD1LJe6GgyEMT:-MuEANUTD1LJe6GgyEMU:bppt7s6) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/appender.rs#L203)):*
> ```XML
>                                 break;
>                             }
>                             StreamOp::Abort => {
> ```

If `StreamOp::Init` weren't needed, it seems like the `StreamOp::Close` vs `StreamOp::Abort` distinction could equivalently be handled by taking a `Stream<Result<bytes::Bytes, E>>` or perhaps `Stream<std::io::Result<bytes::Bytes>>` specifically. An error Result aborts the append, while a clean Stream end (no error) commits the append.

What's nice about this representation is that it can natively work with something like tokio's [ReaderStream](https://docs.rs/tokio-util/0.6.9/tokio_util/io/struct.ReaderStream.html). Which would in turn facilitate writing `AppendService`, which is using files to buffer & accumulate writes and then needs to stream that file content into an `Appender`.
___
*[broker/src/client/appender_test.rs, line 6 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuEEEga3EoQI1oeYZyo:-MuEEEga3EoQI1oeYZyp:b-bu7nso) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/appender_test.rs#L6)):*
> ```XML
> use crate::client::appender::*;
> 
> #[tokio::test]
> ```

It's idiomatic Go to have separate `_test.go` files (and required given how `go test` works). However, AFAIK it's more common in Rust to have smaller unit tests live alongside their implementation, which is how Estuary has written code to-date.

This test is a bit of an in-between, since it requires a broker in the loop. I'd recommend keeping it under the crate's `broker/tests` rather than `broker/src`.
___
*[broker/src/client/retry_test.rs, line 5 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuEF3Xo3V2Sq_BzvU2k:-MuEF3Xp2VK0L1PBetRq:b-hkngb7) ([raw file](https://github.com/adrianbenavides/core-rs/blob/1ee677c0e8426697e5a59f6087bd78b1474009f7/broker/src/client/retry_test.rs#L5)):*
> ```XML
> #[test]
> fn backoff_durations() {
>     let mut test_cases = [
> ```

nit: this test should live within `retry.rs`.

**Comment by adrianbenavides** [comment]
> The gRPC internals also keep a buffer, and the protocol will further have an in-flight buffer between server & client that's dynamically negotiated. I would think this specific buffer size can be quite tight, perhaps just one.

I did different tests with this parameter and I got different results. When appending small chunks of data, it just sends 2 frames before receiving a `WindowUpdate`. With a buffer of 1000, it sends 128 frames. Since this is something it receives from the broker, perhaps it's irrelevant. Just wanted to say this out loud in case it's important. For now I'll set the buffer size to 1.

```
// buffer=1000
h2::codec::framed_write: send frame=Data { stream_id: StreamId(1) }
h2::codec::framed_write: send frame=Data { stream_id: StreamId(1) }
h2::codec::framed_write: send frame=Data { stream_id: StreamId(1) }
h2::codec::framed_write: send frame=Data { stream_id: StreamId(1) }
h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 1280 }
h2::codec::framed_read: received frame=Ping { ack: false, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
h2::codec::framed_write: send frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
```

vs 

```
// buffer=1
h2::codec::framed_write: send frame=Data { stream_id: StreamId(1) }
h2::codec::framed_write: send frame=Data { stream_id: StreamId(1) }
h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 20 }
h2::codec::framed_read: received frame=Ping { ack: false, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
h2::codec::framed_write: send frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
```

> Not looking for changes right now, just want to talk through this: how did you decide between this imperative API with an internal stream channel, vs one where the appender takes a stream of > StreamOp?

I was just looking to simplify the usage from both the `append` method and individually from the `write`, `close`... methods. Although, now that I now that the `append` method is not necessary, it could probably be done differently.

Not sure if I'm understanding the other approach you mentioned. If the appender takes a stream of StreamOp's, then the async stream should be created outside of the `Appender`. If that's the case, without giving it too much thinking, I think it would complicate the management of the stream. I could extend more on this if you give more details.

> FWIW, I wouldn't really consider that part of the Appender interface, but absolutely see how that's confusing given the context. 
> Perhaps it should live in the broker::client module? To my knowledge, Append() isn't much used outside of some limited test-case uses. ...

OK, that's exactly what happened, it looked like this `append` method was the entry point of the `Appender`. I'll delete it then!

> This should probably take bytes::Bytes to avoid copies.

I didn't do that because you have to convert the buffer into a `Vec<u8>` when building the request either way. Probably the code using the `Appender` (the `AppendService` I suspect) will indeed have to use `bytes::Bytes` if it reads a chunk more than once. Anyway, I'll do the change anyway to enforce its usage from above.

> ... _stream()_ comments

I'll check every comment regarding this method and come back with what I've done. I think it can be greatly improved with your suggestions.

Thanks for the thorough review!

**Comment by adrianbenavides** [comment]
> If StreamOp::Init weren't needed, it seems like the StreamOp::Close vs StreamOp::Abort distinction could equivalently be handled by taking a Stream<Result<bytes::Bytes, E>> or perhaps Stream<std::io::Result<bytes::Bytes>> specifically. An error Result aborts the append, while a clean Stream end (no error) commits the append.

I have deleted the `StreamOp::Init` variant but I don't understand how to merge the Close and Abort variants. The usage of these variants in the go implementation is:

```go
var app = client.NewAppender(ctx, rjc, pb.AppendRequest{Journal: journal})
if _, err = io.Copy(app, input); err == nil {
    err = app.Close()
} else {
    app.Abort()
}
```

then, in rust would be something like:

```rust
let mut app = Appender::new(rjc, request)?;
let mut write_buf = Vec::new();
input.read_to_end(&mut write_buf).await?;
app.write(write_buf).await?;

// If we have an error here it means there was no commit, so the Abort is implicit.
app.close().await?; 
```

If this is always the use case, then the Abort operation makes no sense. What made me add that operation was that I thought that there could be a use case where you want to abort while writing into the stream _before_ closing it. But I'm not seeing any case like this in the go codebase. Does this make sense?

**Comment by adrianbenavides** [comment]
So far, I've found two different usages, in `gazctlcmd`, where an `Appender` instance is created and consumed:

```go
var app = client.NewAppender(ctx, rjc, pb.AppendRequest{Journal: journal})
if _, err = io.Copy(app, input); err == nil {
    err = app.Close()
} else {
    app.Abort()
}
```

and in `serveAppends` (within AppenderService), where a single `Appender` instance is used several times:

```go
var _, err2 = io.Copy(&aa.app, io.NewSectionReader(aa.fb.file, 0, aa.checkpoint))
if err2 == nil {
    err2 = aa.app.Close()
}
```

After our talk, this is how it would look in rust. In order to support the AppenderService usage, the `append` method doesn't consume the instance and hence it must clone the `rjc` and `req`:

```rust
let appender = Appender::new(rjc, req).await?;
let res = appender
    .append(reader)
    .await?;
```

The only thing that I can't figure out is how to simplify the stream appends:

```rust
pub async fn append<Reader>(&self, reader: Reader) -> ClientResult<pb::AppendResponse>
where
    Reader: tokio::io::AsyncRead + Send + Sync + 'static + Unpin,
{
    let (buf_tx, buf_rx) = mpsc::channel(1);
    let (res_tx, res_rx) = oneshot::channel();
    let request = self.request.clone();
    let mut rjc = self.rjc.clone();
    tokio::spawn(async move {
        let stream = Self::stream(request, buf_rx);
        let res = rjc.client.append(stream).await;
        let _ = res_tx.send(res);
    });
    Self::write(&buf_tx, reader).await?; // The reader is converted into ReaderStream here.
    Self::close(&buf_tx, res_rx).await
}
```

The input reader only contains the writes, but I still need the first and last requests to complete the RPC, and that forces me to have that second stream in the background to process all requests.

**Review by jgraettinger — COMMENTED** [review]
Here's a sketch of what I was thinking (I've not tried compiling this -- it may be that `inner_err` needs to be a one-shot):

```rust
pub async fn append(
    mut rjc: pb_ext::RoutedJournalClient,
    request: pb::AppendRequest,
    stream: Stream<std::io::Result<bytes::Bytes>>
) -> ClientResult<pb::AppendResponse>
{
        mut inner_err : Option<std::io::Error> = None;

        let inner = async_stream::stream! {
            yield request; // Send append request metadata as first message.

            loop {
                match stream.recv().await {
                    None => {
                        // Clean EOF of |stream|. Commit by sending empty AppendRequest, then close.
                        yield pb::AppendRequest::default();
                        return;
                    }
                    Some(Ok(content)) if !content.is_empty() => {
                        // Send non-empty content to broker.
                        yield pb::AppendRequest{content: content.to_vec(), ..Default::default};
                    }
                    Some(Err(err)) => {
                        // Internal error. Retain it, and return _without_ sending an empty AppendRequest.
                        // The broker will treat this as a roll-back.
                        inner_err = Some(err);
                        return;
                    }
                }
            }
        };
        let response = rjc.client.append(inner).await;

        // Inspect inner_err, and return an overall operation Result which preferentially surfaces
        // a Some |inner_err|, and if that's None then the actual response
        ...
}

```

> *[Reviewable](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-:-MuIB7O4Bs7W5hQHCVjs:bv8vav2)* status: all files reviewed, 9 unresolved discussions (waiting on @adrianbenavides)

**Comment by adrianbenavides** [comment]
So obvious and I couldn't see it :facepalm: I've added a new commit with all these changes. I think is looking great now, thanks for all the help @jgraettinger!

**Review by jgraettinger — APPROVED** [review]
LGTM! % a couple of nits

(As a bit of protocol if you haven't seen it, a "LGTM % ..." means there's a bit of feedback left in the review which may require updates, but that the reviewer think it's good to land without another subsequent review pass).

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-:-MuMT8r_CbnXrnouryQ7:b-ccrbap)* status: all files reviewed, 2 unresolved discussions (waiting on @adrianbenavides)

___
*[broker/src/client/appender.rs, line 48 at r2](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuMQXxJ7gnRgS4_ov_v:-MuMQXxJ7gnRgS4_ov_w:b-jopnb) ([raw file](https://github.com/adrianbenavides/core-rs/blob/e043092a91c9fac0f75fc7af3aa7923b8d8a3312/broker/src/client/appender.rs#L48)):*
> ```XML
> 
>     /// Append the contents of a `Stream` to a journal as a single Append transaction.
>     pub async fn append<Reader>(&mut self, reader: Reader) -> ClientResult<pb::AppendResponse>
> ```

nit: rename `reader` => `stream`, Reader => S or similar? I was confused for a moment thinking this was an AsyncRead, but it's a Stream.
Applies to stream() below as well.
___
*[broker/src/client/appender.rs, line 59 at r2](https://reviewable.io/reviews/adrianbenavides/core-rs/1#-MuMPeyO6PCGQ9Sf4cxv:-MuMPeyO6PCGQ9Sf4cxw:buhnpos) ([raw file](https://github.com/adrianbenavides/core-rs/blob/e043092a91c9fac0f75fc7af3aa7923b8d8a3312/broker/src/client/appender.rs#L59)):*
> ```XML
>             _ => {
>                 // The channel was closed along with the stream. Proceed with processing the RPC result.
>                 match rpc_result {
> ```

nit: you can further simplify / de-indent this by matching over `(stream_err_rx.await, rpc_result)` jointly, with cases like `(Ok(stream_err), _) => {}`, `(None, Ok(res)) => ` and so on.

**Pull request merged**
